<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="3rd\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="BouncyCastle.Cryptography">
      <HintPath>3rd\BouncyCastle.Cryptography.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
