services:
  eva:
    image: golang:latest
    container_name: eva
    network_mode: host
    privileged: true
    tty: true
    stdin_open: true
    working_dir: /home/go
    command: ./eva
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - ./:/home/go/
