services:
  noah:
    image: ubuntu:26.04
    container_name: noah
    network_mode: host
    privileged: true
    tty: true
    stdin_open: true
    working_dir: /usr/local/bin
    command: ./noah
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - ./:/usr/local/bin/
