SELECT SLEEP(10);

CREATE USER 'admin'@'%' IDENTIFIED BY 'aa113311..';
GRANT SYSTEM_VARIABLES_ADMIN, SYSTEM_USER, REPLICATION_SLAVE_ADMIN, CONNECTION_ADMIN, PROCESS, SUPER ON *.* TO 'admin'@'%';
FLUSH PRIVILEGES;

STOP REPLICA;
RESET REPLICA ALL;
CHANGE REPLICATION SOURCE TO SOURCE_HOST='192.168.1.161',
SOURCE_USER="admin",
SOURCE_PASSWORD='aa113311..',
SOURCE_LOG_FILE="binlog.000002",
SOURCE_PORT=3306,
SOURCE_LOG_POS=158,
GET_SOURCE_PUBLIC_KEY=1;
START REPLICA;

-- 在从库上执行，禁止所有用户的写操作
-- SET GLOBAL super_read_only=1;
-- SHOW replica STATUS