server:
  id: 0x10000000
  timeout: 45
  protocol: "kcp"
  name: "moses"
  host: "13.212.170.186:5555"
  desc: "网关"


etcd:
  url: "http://13.212.159.179:2379"
  user: "root"
  pass: "123456"
  ttl: 15


ifname: "lo"
kcp_bpf_path: "kcp.bpf.o"
envelope_bpf_path: "envelope.bpf.o"

prof_path: "moses.prof"
log_path: "logs"

sndbuf: 16777216
rcvbuf: 33554432

sndwnd: 128
rcvwnd: 128

nodelay: 1
interval: 10
resend: 3
nc: 1

newsess_max: 32 #每个源 IP 每秒允许多少个"新会话尝试", 0 = 不限速

nsiphash: 256
ed25519_pk: "OjvxWlrli0k+EDeNwWDMMTyXWpXtizQyifq8tn+bBck="
# ed25519_sk: "49snRJko0ayMemUHsZ5c7qj6X0Iq09np7NQBu6njl7w6O/FaWuWLST4QN43BYMwxPJdale2LNDKJ+ry2f5sFyQ=="
