services:
  chat:
    image: ubuntu:26.04
    container_name: chat
    network_mode: host
    privileged: true
    tty: true
    stdin_open: true
    working_dir: /usr/local/bin
    command: ./server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - ./server:/usr/local/bin/server