services:
  cerberus:
    image: ubuntu:26.04
    container_name: cerberus
    network_mode: host
    privileged: true
    tty: true
    stdin_open: true
    working_dir: /home/cerberus
    command: ./cerberus
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - ./:/home/cerberus
