<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <ApplicationIcon>Resources\app.ico</ApplicationIcon>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	<DefineConstants>WINDOWS</DefineConstants>
	<!-- <DefineConstants>MACOS</DefineConstants> -->
	<!-- <DefineConstants>LINUX</DefineConstants> -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Google.Protobuf" Version="3.35.1" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Resources/**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\lilith\Lilith.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controls\Contact\" />
    <Folder Include="Controls\Org\" />
    <Folder Include="Proto\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Controls\Settings\SettingInfoPanel.axaml.cs">
      <DependentUpon>SettingInfoPanel.axaml</DependentUpon>
    </Compile>
    <Compile Update="Controls\Settings\SettingSecurityPanel.axaml.cs">
      <DependentUpon>SettingSecurityPanel.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
