SELECT SLEEP(10);

CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'aa113311..';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;

CREATE USER IF NOT EXISTS 'admin'@'%' IDENTIFIED WITH caching_sha2_password BY 'aa113311..' REQUIRE NONE;
GRANT REPLICATION SLAVE ON *.* TO 'admin'@'%';

FLUSH PRIVILEGES;

# SHOW BINARY LOG STATUS;