// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ccs.proto
// Protobuf C++ Version: 7.36.0-rc2

#ifndef ccs_2eproto_2epb_2eh
#define ccs_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7036000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_util.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ccs_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_ccs_2eproto {
  static const ::uint32_t offsets[];
};
namespace ccs {
enum MessageType : int;
extern const uint32_t MessageType_internal_data_[];
class SingleChatReq;
struct SingleChatReqGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern SingleChatReqGlobalsTypeInternal SingleChatReq_globals_;
extern const ::google::protobuf::internal::ClassDataLite SingleChatReq_class_data_;
#else
extern const SingleChatReqGlobalsTypeInternal SingleChatReq_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
class SingleChatRsp;
struct SingleChatRspGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern SingleChatRspGlobalsTypeInternal SingleChatRsp_globals_;
extern const ::google::protobuf::internal::ClassDataLite SingleChatRsp_class_data_;
#else
extern const SingleChatRspGlobalsTypeInternal SingleChatRsp_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
}  // namespace ccs
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::ccs::MessageType_internal_data_>
    internal::EnumTraitsImpl::value<::ccs::MessageType>;
}  // namespace protobuf
}  // namespace google

namespace ccs {
enum MessageType : int {
  MT_None = 0,
  MT_Text = 1,
  MT_Image = 2,
  MT_File = 3,
  MT_Audio = 4,
  MT_Video = 5,
  MT_Pdf = 6,
  MT_Edit = 100,
  MT_Revoke = 101,
  MessageType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  MessageType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t MessageType_internal_data_[];
inline constexpr MessageType MessageType_MIN =
    static_cast<MessageType>(0);
inline constexpr MessageType MessageType_MAX =
    static_cast<MessageType>(101);
[[nodiscard]] inline bool MessageType_IsValid(int value) {
  return ::google::protobuf::internal::ValidateEnum(value, MessageType_internal_data_);
}
inline constexpr int MessageType_ARRAYSIZE = 101 + 1;
[[nodiscard]] const ::std::string& MessageType_Name(MessageType value);
template <typename T>
[[nodiscard]] const ::std::string& MessageType_Name(T value) {
  static_assert(::std::is_same<T, MessageType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to MessageType_Name().");
  return MessageType_Name(static_cast<MessageType>(value));
}
[[nodiscard]] bool MessageType_Parse(
    ::absl::string_view name, MessageType* PROTOBUF_NONNULL value);
using ::google::protobuf::internal::generated_enum::AbslParseFlag;
using ::google::protobuf::internal::generated_enum::AbslUnparseFlag;

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED SingleChatRsp final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:ccs.SingleChatRsp) */ {
  using Super_ = ::google::protobuf::MessageLite;

 public:
  inline SingleChatRsp() : SingleChatRsp(nullptr) {}
  ~SingleChatRsp() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SingleChatRsp* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SingleChatRsp));
  }
#endif

  template <typename = void>
  explicit constexpr SingleChatRsp(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline SingleChatRsp(const SingleChatRsp& from) : SingleChatRsp(nullptr, from) {}
  inline SingleChatRsp(SingleChatRsp&& from) noexcept : SingleChatRsp(nullptr, ::std::move(from)) {}
  inline SingleChatRsp& operator=(const SingleChatRsp& from) {
    CopyFrom(from);
    return *this;
  }
  inline SingleChatRsp& operator=(SingleChatRsp&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  [[nodiscard]] inline ::std::string* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  [[nodiscard]] static const SingleChatRsp& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<SingleChatRsp>(&SingleChatRsp_globals_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(SingleChatRsp& a, SingleChatRsp& b) { a.Swap(&b); }
  inline void Swap(SingleChatRsp* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SingleChatRsp* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] SingleChatRsp* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return Super_::DefaultConstruct<SingleChatRsp>(arena);
  }
  void CopyFrom(const SingleChatRsp& from);
  void MergeFrom(const SingleChatRsp& from) { SingleChatRsp::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SingleChatRsp* PROTOBUF_NONNULL other);
 private:
  static ::absl::string_view FullMessageName() { return "ccs.SingleChatRsp"; }

  explicit SingleChatRsp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SingleChatRsp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SingleChatRsp& from);
  SingleChatRsp(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SingleChatRsp&& from) noexcept
      : SingleChatRsp(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCliUuidFieldNumber = 1,
    kSeqFieldNumber = 3,
    kMsgIdFieldNumber = 4,
    kCreatedAtFieldNumber = 5,
    kCodeFieldNumber = 2,
  };
  // string cli_uuid = 1;
  void clear_cli_uuid() ;
  [[nodiscard]] const ::std::string& cli_uuid() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_cli_uuid(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_cli_uuid();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_cli_uuid();
  void set_allocated_cli_uuid(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_cli_uuid() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_cli_uuid(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_cli_uuid();

  public:
  // int64 seq = 3;
  void clear_seq() ;
  [[nodiscard]] ::int64_t seq() const;
  void set_seq(::int64_t value);

  private:
  ::int64_t _internal_seq() const;
  void _internal_set_seq(::int64_t value);

  public:
  // int64 msg_id = 4;
  void clear_msg_id() ;
  [[nodiscard]] ::int64_t msg_id() const;
  void set_msg_id(::int64_t value);

  private:
  ::int64_t _internal_msg_id() const;
  void _internal_set_msg_id(::int64_t value);

  public:
  // int64 created_at = 5;
  void clear_created_at() ;
  [[nodiscard]] ::int64_t created_at() const;
  void set_created_at(::int64_t value);

  private:
  ::int64_t _internal_created_at() const;
  void _internal_set_created_at(::int64_t value);

  public:
  // int32 code = 2;
  void clear_code() ;
  [[nodiscard]] ::int32_t code() const;
  void set_code(::int32_t value);

  private:
  ::int32_t _internal_code() const;
  void _internal_set_code(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:ccs.SingleChatRsp)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<3, 5,
                          0, 34,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SingleChatRsp& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr cli_uuid_;
    ::int64_t seq_;
    ::int64_t msg_id_;
    ::int64_t created_at_;
    ::int32_t code_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ccs_2eproto;
};
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED SingleChatReq final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:ccs.SingleChatReq) */ {
  using Super_ = ::google::protobuf::MessageLite;

 public:
  inline SingleChatReq() : SingleChatReq(nullptr) {}
  ~SingleChatReq() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SingleChatReq* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SingleChatReq));
  }
#endif

  template <typename = void>
  explicit constexpr SingleChatReq(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline SingleChatReq(const SingleChatReq& from) : SingleChatReq(nullptr, from) {}
  inline SingleChatReq(SingleChatReq&& from) noexcept : SingleChatReq(nullptr, ::std::move(from)) {}
  inline SingleChatReq& operator=(const SingleChatReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline SingleChatReq& operator=(SingleChatReq&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  [[nodiscard]] inline ::std::string* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  [[nodiscard]] static const SingleChatReq& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<SingleChatReq>(&SingleChatReq_globals_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(SingleChatReq& a, SingleChatReq& b) { a.Swap(&b); }
  inline void Swap(SingleChatReq* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SingleChatReq* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] SingleChatReq* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return Super_::DefaultConstruct<SingleChatReq>(arena);
  }
  void CopyFrom(const SingleChatReq& from);
  void MergeFrom(const SingleChatReq& from) { SingleChatReq::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SingleChatReq* PROTOBUF_NONNULL other);
 private:
  static ::absl::string_view FullMessageName() { return "ccs.SingleChatReq"; }

  explicit SingleChatReq(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SingleChatReq(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SingleChatReq& from);
  SingleChatReq(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SingleChatReq&& from) noexcept
      : SingleChatReq(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCliUuidFieldNumber = 1,
    kContentFieldNumber = 4,
    kToIdFieldNumber = 2,
    kTypeFieldNumber = 3,
    kTargetIdFieldNumber = 5,
    kTargetSeqFieldNumber = 6,
  };
  // string cli_uuid = 1;
  void clear_cli_uuid() ;
  [[nodiscard]] const ::std::string& cli_uuid() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_cli_uuid(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_cli_uuid();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_cli_uuid();
  void set_allocated_cli_uuid(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_cli_uuid() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_cli_uuid(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_cli_uuid();

  public:
  // string content = 4;
  void clear_content() ;
  [[nodiscard]] const ::std::string& content() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_content(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_content();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_content();
  void set_allocated_content(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_content() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_content(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_content();

  public:
  // uint32 to_id = 2;
  void clear_to_id() ;
  [[nodiscard]] ::uint32_t to_id() const;
  void set_to_id(::uint32_t value);

  private:
  ::uint32_t _internal_to_id() const;
  void _internal_set_to_id(::uint32_t value);

  public:
  // .ccs.MessageType type = 3;
  void clear_type() ;
  [[nodiscard]] ::ccs::MessageType type() const;
  void set_type(::ccs::MessageType value);

  private:
  ::ccs::MessageType _internal_type() const;
  void _internal_set_type(::ccs::MessageType value);

  public:
  // int64 target_id = 5;
  void clear_target_id() ;
  [[nodiscard]] ::int64_t target_id() const;
  void set_target_id(::int64_t value);

  private:
  ::int64_t _internal_target_id() const;
  void _internal_set_target_id(::int64_t value);

  public:
  // int64 target_seq = 6;
  void clear_target_seq() ;
  [[nodiscard]] ::int64_t target_seq() const;
  void set_target_seq(::int64_t value);

  private:
  ::int64_t _internal_target_seq() const;
  void _internal_set_target_seq(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:ccs.SingleChatReq)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<3, 6,
                          0, 41,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SingleChatReq& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr cli_uuid_;
    ::google::protobuf::internal::ArenaStringPtr content_;
    ::uint32_t to_id_;
    int type_;
    ::int64_t target_id_;
    ::int64_t target_seq_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ccs_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SingleChatReq

// string cli_uuid = 1;
inline void SingleChatReq::clear_cli_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cli_uuid_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::std::string& SingleChatReq::cli_uuid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ccs.SingleChatReq.cli_uuid)
  return _internal_cli_uuid();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void SingleChatReq::set_cli_uuid(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.cli_uuid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ccs.SingleChatReq.cli_uuid)
}
inline ::std::string* PROTOBUF_NONNULL SingleChatReq::mutable_cli_uuid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_cli_uuid();
  // @@protoc_insertion_point(field_mutable:ccs.SingleChatReq.cli_uuid)
  return _s;
}
inline const ::std::string& SingleChatReq::_internal_cli_uuid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cli_uuid_.Get();
}
inline void SingleChatReq::_internal_set_cli_uuid(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cli_uuid_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL SingleChatReq::_internal_mutable_cli_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.cli_uuid_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE SingleChatReq::release_cli_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ccs.SingleChatReq.cli_uuid)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.cli_uuid_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.cli_uuid_.Set("", GetArena());
  }
  return released;
}
inline void SingleChatReq::set_allocated_cli_uuid(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.cli_uuid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.cli_uuid_.IsDefault()) {
    _impl_.cli_uuid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ccs.SingleChatReq.cli_uuid)
}

// uint32 to_id = 2;
inline void SingleChatReq::clear_to_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.to_id_ = 0u;
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
inline ::uint32_t SingleChatReq::to_id() const {
  // @@protoc_insertion_point(field_get:ccs.SingleChatReq.to_id)
  return _internal_to_id();
}
inline void SingleChatReq::set_to_id(::uint32_t value) {
  _internal_set_to_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:ccs.SingleChatReq.to_id)
}
inline ::uint32_t SingleChatReq::_internal_to_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.to_id_;
}
inline void SingleChatReq::_internal_set_to_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.to_id_ = value;
}

// .ccs.MessageType type = 3;
inline void SingleChatReq::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
}
inline ::ccs::MessageType SingleChatReq::type() const {
  // @@protoc_insertion_point(field_get:ccs.SingleChatReq.type)
  return _internal_type();
}
inline void SingleChatReq::set_type(::ccs::MessageType value) {
  _internal_set_type(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:ccs.SingleChatReq.type)
}
inline ::ccs::MessageType SingleChatReq::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::ccs::MessageType>(_impl_.type_);
}
inline void SingleChatReq::_internal_set_type(::ccs::MessageType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// string content = 4;
inline void SingleChatReq::clear_content() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.content_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline const ::std::string& SingleChatReq::content() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ccs.SingleChatReq.content)
  return _internal_content();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void SingleChatReq::set_content(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.content_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ccs.SingleChatReq.content)
}
inline ::std::string* PROTOBUF_NONNULL SingleChatReq::mutable_content()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_content();
  // @@protoc_insertion_point(field_mutable:ccs.SingleChatReq.content)
  return _s;
}
inline const ::std::string& SingleChatReq::_internal_content() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.content_.Get();
}
inline void SingleChatReq::_internal_set_content(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.content_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL SingleChatReq::_internal_mutable_content() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.content_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE SingleChatReq::release_content() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ccs.SingleChatReq.content)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.content_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.content_.Set("", GetArena());
  }
  return released;
}
inline void SingleChatReq::set_allocated_content(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.content_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.content_.IsDefault()) {
    _impl_.content_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ccs.SingleChatReq.content)
}

// int64 target_id = 5;
inline void SingleChatReq::clear_target_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.target_id_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
}
inline ::int64_t SingleChatReq::target_id() const {
  // @@protoc_insertion_point(field_get:ccs.SingleChatReq.target_id)
  return _internal_target_id();
}
inline void SingleChatReq::set_target_id(::int64_t value) {
  _internal_set_target_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:ccs.SingleChatReq.target_id)
}
inline ::int64_t SingleChatReq::_internal_target_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.target_id_;
}
inline void SingleChatReq::_internal_set_target_id(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.target_id_ = value;
}

// int64 target_seq = 6;
inline void SingleChatReq::clear_target_seq() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.target_seq_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
}
inline ::int64_t SingleChatReq::target_seq() const {
  // @@protoc_insertion_point(field_get:ccs.SingleChatReq.target_seq)
  return _internal_target_seq();
}
inline void SingleChatReq::set_target_seq(::int64_t value) {
  _internal_set_target_seq(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:ccs.SingleChatReq.target_seq)
}
inline ::int64_t SingleChatReq::_internal_target_seq() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.target_seq_;
}
inline void SingleChatReq::_internal_set_target_seq(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.target_seq_ = value;
}

// -------------------------------------------------------------------

// SingleChatRsp

// string cli_uuid = 1;
inline void SingleChatRsp::clear_cli_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cli_uuid_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::std::string& SingleChatRsp::cli_uuid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ccs.SingleChatRsp.cli_uuid)
  return _internal_cli_uuid();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void SingleChatRsp::set_cli_uuid(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.cli_uuid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ccs.SingleChatRsp.cli_uuid)
}
inline ::std::string* PROTOBUF_NONNULL SingleChatRsp::mutable_cli_uuid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_cli_uuid();
  // @@protoc_insertion_point(field_mutable:ccs.SingleChatRsp.cli_uuid)
  return _s;
}
inline const ::std::string& SingleChatRsp::_internal_cli_uuid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cli_uuid_.Get();
}
inline void SingleChatRsp::_internal_set_cli_uuid(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cli_uuid_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL SingleChatRsp::_internal_mutable_cli_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.cli_uuid_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE SingleChatRsp::release_cli_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ccs.SingleChatRsp.cli_uuid)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.cli_uuid_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.cli_uuid_.Set("", GetArena());
  }
  return released;
}
inline void SingleChatRsp::set_allocated_cli_uuid(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.cli_uuid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.cli_uuid_.IsDefault()) {
    _impl_.cli_uuid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ccs.SingleChatRsp.cli_uuid)
}

// int32 code = 2;
inline void SingleChatRsp::clear_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.code_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
}
inline ::int32_t SingleChatRsp::code() const {
  // @@protoc_insertion_point(field_get:ccs.SingleChatRsp.code)
  return _internal_code();
}
inline void SingleChatRsp::set_code(::int32_t value) {
  _internal_set_code(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:ccs.SingleChatRsp.code)
}
inline ::int32_t SingleChatRsp::_internal_code() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.code_;
}
inline void SingleChatRsp::_internal_set_code(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.code_ = value;
}

// int64 seq = 3;
inline void SingleChatRsp::clear_seq() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.seq_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline ::int64_t SingleChatRsp::seq() const {
  // @@protoc_insertion_point(field_get:ccs.SingleChatRsp.seq)
  return _internal_seq();
}
inline void SingleChatRsp::set_seq(::int64_t value) {
  _internal_set_seq(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:ccs.SingleChatRsp.seq)
}
inline ::int64_t SingleChatRsp::_internal_seq() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.seq_;
}
inline void SingleChatRsp::_internal_set_seq(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.seq_ = value;
}

// int64 msg_id = 4;
inline void SingleChatRsp::clear_msg_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msg_id_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
inline ::int64_t SingleChatRsp::msg_id() const {
  // @@protoc_insertion_point(field_get:ccs.SingleChatRsp.msg_id)
  return _internal_msg_id();
}
inline void SingleChatRsp::set_msg_id(::int64_t value) {
  _internal_set_msg_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:ccs.SingleChatRsp.msg_id)
}
inline ::int64_t SingleChatRsp::_internal_msg_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.msg_id_;
}
inline void SingleChatRsp::_internal_set_msg_id(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msg_id_ = value;
}

// int64 created_at = 5;
inline void SingleChatRsp::clear_created_at() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.created_at_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
}
inline ::int64_t SingleChatRsp::created_at() const {
  // @@protoc_insertion_point(field_get:ccs.SingleChatRsp.created_at)
  return _internal_created_at();
}
inline void SingleChatRsp::set_created_at(::int64_t value) {
  _internal_set_created_at(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:ccs.SingleChatRsp.created_at)
}
inline ::int64_t SingleChatRsp::_internal_created_at() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.created_at_;
}
inline void SingleChatRsp::_internal_set_created_at(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.created_at_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace ccs


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::ccs::MessageType> : std::true_type {};
template <>
struct internal::LiteEnumFuncs<::ccs::MessageType> {
  static constexpr bool kIsDefined = true;
  static constexpr auto kParseFunc = ::ccs::MessageType_Parse;
  static constexpr auto kNameFunc = ::ccs::MessageType_Name<int>;
};

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // ccs_2eproto_2epb_2eh
