// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ccs.proto
// Protobuf C++ Version: 7.36.0-rc2

#include "ccs.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace ccs {
class SingleChatRsp::_Internal {
 public:
  using HasBits = decltype(::std::declval<SingleChatRsp>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SingleChatRsp, _impl_._has_bits_);
};

constexpr SingleChatRsp::ParseTableT_ SingleChatRsp::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(SingleChatRsp, _impl_._has_bits_),
      0, // no _extensions_
      5, 56,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967264,  // skipmap
      offsetof(ParseTableT_, field_entries),
      5,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::MpUnknownFields,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::ccs::SingleChatRsp>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
      // string cli_uuid = 1;
      {::_pbi::TcParser::FastUS1,
       {10, 0, 0,
        PROTOBUF_FIELD_OFFSET(SingleChatRsp, _impl_.cli_uuid_)}},
      // int32 code = 2;
      {::_pbi::TcParser::FastV32S1,
       {16, 4, 0,
        PROTOBUF_FIELD_OFFSET(SingleChatRsp, _impl_.code_)}},
      // int64 seq = 3;
      {::_pbi::TcParser::FastV64S1,
       {24, 1, 0,
        PROTOBUF_FIELD_OFFSET(SingleChatRsp, _impl_.seq_)}},
      // int64 msg_id = 4;
      {::_pbi::TcParser::FastV64S1,
       {32, 2, 0,
        PROTOBUF_FIELD_OFFSET(SingleChatRsp, _impl_.msg_id_)}},
      // int64 created_at = 5;
      {::_pbi::TcParser::FastV64S1,
       {40, 3, 0,
        PROTOBUF_FIELD_OFFSET(SingleChatRsp, _impl_.created_at_)}},
      {::_pbi::TcParser::MiniParse, {}},
      {::_pbi::TcParser::MiniParse, {}},
    }}, {{
      65535, 65535
    }}, {{
      // string cli_uuid = 1;
      {PROTOBUF_FIELD_OFFSET(SingleChatRsp, _impl_.cli_uuid_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // int32 code = 2;
      {PROTOBUF_FIELD_OFFSET(SingleChatRsp, _impl_.code_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
      // int64 seq = 3;
      {PROTOBUF_FIELD_OFFSET(SingleChatRsp, _impl_.seq_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
      // int64 msg_id = 4;
      {PROTOBUF_FIELD_OFFSET(SingleChatRsp, _impl_.msg_id_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
      // int64 created_at = 5;
      {PROTOBUF_FIELD_OFFSET(SingleChatRsp, _impl_.created_at_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    }},
    // no aux_entries
    {{
      "\21\10\0\0\0\0\0\0"
      "ccs.SingleChatRsp"
      "cli_uuid"
    }},
  };
}


inline constexpr SingleChatRsp::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : cli_uuid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        seq_{::int64_t{0}},
        msg_id_{::int64_t{0}},
        created_at_{::int64_t{0}},
        code_{0} {}

template <typename>
constexpr SingleChatRsp::SingleChatRsp(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : Super_(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL SingleChatRsp::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SingleChatRsp(arena);
}
constexpr auto SingleChatRsp::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(SingleChatRsp), alignof(SingleChatRsp));
}
constexpr auto SingleChatRsp::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataLite{
      {
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &SingleChatRsp::MergeImpl,
          Super_::GetNewImpl<SingleChatRsp>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SingleChatRsp::SharedDtor,
          Super_::GetClearImpl<SingleChatRsp>(), &SingleChatRsp::ByteSizeLong,
              &SingleChatRsp::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SingleChatRsp, _impl_._cached_size_),
          true,
      },
      "ccs.SingleChatRsp",
  };
}
struct SingleChatRspGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr SingleChatRspGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 SingleChatRsp_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(SingleChatRsp::InternalGenerateClassData_(
            _default, &SingleChatRsp_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<SingleChatRsp>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~SingleChatRspGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) SingleChatRsp _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<SingleChatRsp>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(SingleChatRspGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST SingleChatRspGlobalsTypeInternal SingleChatRsp_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* SingleChatRsp_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return SingleChatRsp_globals_.GetClassData();
#else
  return SingleChatRsp_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class SingleChatReq::_Internal {
 public:
  using HasBits = decltype(::std::declval<SingleChatReq>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SingleChatReq, _impl_._has_bits_);
};

constexpr SingleChatReq::ParseTableT_ SingleChatReq::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(SingleChatReq, _impl_._has_bits_),
      0, // no _extensions_
      6, 56,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967232,  // skipmap
      offsetof(ParseTableT_, field_entries),
      6,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::MpUnknownFields,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::ccs::SingleChatReq>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
      // string cli_uuid = 1;
      {::_pbi::TcParser::FastUS1,
       {10, 0, 0,
        PROTOBUF_FIELD_OFFSET(SingleChatReq, _impl_.cli_uuid_)}},
      // uint32 to_id = 2;
      {::_pbi::TcParser::FastV32S1,
       {16, 2, 0,
        PROTOBUF_FIELD_OFFSET(SingleChatReq, _impl_.to_id_)}},
      // .ccs.MessageType type = 3;
      {::_pbi::TcParser::FastV32S1,
       {24, 3, 0,
        PROTOBUF_FIELD_OFFSET(SingleChatReq, _impl_.type_)}},
      // string content = 4;
      {::_pbi::TcParser::FastUS1,
       {34, 1, 0,
        PROTOBUF_FIELD_OFFSET(SingleChatReq, _impl_.content_)}},
      // int64 target_id = 5;
      {::_pbi::TcParser::FastV64S1,
       {40, 4, 0,
        PROTOBUF_FIELD_OFFSET(SingleChatReq, _impl_.target_id_)}},
      // int64 target_seq = 6;
      {::_pbi::TcParser::FastV64S1,
       {48, 5, 0,
        PROTOBUF_FIELD_OFFSET(SingleChatReq, _impl_.target_seq_)}},
      {::_pbi::TcParser::MiniParse, {}},
    }}, {{
      65535, 65535
    }}, {{
      // string cli_uuid = 1;
      {PROTOBUF_FIELD_OFFSET(SingleChatReq, _impl_.cli_uuid_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // uint32 to_id = 2;
      {PROTOBUF_FIELD_OFFSET(SingleChatReq, _impl_.to_id_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
      // .ccs.MessageType type = 3;
      {PROTOBUF_FIELD_OFFSET(SingleChatReq, _impl_.type_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
      // string content = 4;
      {PROTOBUF_FIELD_OFFSET(SingleChatReq, _impl_.content_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // int64 target_id = 5;
      {PROTOBUF_FIELD_OFFSET(SingleChatReq, _impl_.target_id_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
      // int64 target_seq = 6;
      {PROTOBUF_FIELD_OFFSET(SingleChatReq, _impl_.target_seq_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    }},
    // no aux_entries
    {{
      "\21\10\0\0\7\0\0\0"
      "ccs.SingleChatReq"
      "cli_uuid"
      "content"
    }},
  };
}


inline constexpr SingleChatReq::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : cli_uuid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        content_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        to_id_{0u},
        type_{static_cast< ::ccs::MessageType >(0)},
        target_id_{::int64_t{0}},
        target_seq_{::int64_t{0}} {}

template <typename>
constexpr SingleChatReq::SingleChatReq(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : Super_(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL SingleChatReq::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SingleChatReq(arena);
}
constexpr auto SingleChatReq::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(SingleChatReq), alignof(SingleChatReq));
}
constexpr auto SingleChatReq::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataLite{
      {
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &SingleChatReq::MergeImpl,
          Super_::GetNewImpl<SingleChatReq>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SingleChatReq::SharedDtor,
          Super_::GetClearImpl<SingleChatReq>(), &SingleChatReq::ByteSizeLong,
              &SingleChatReq::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SingleChatReq, _impl_._cached_size_),
          true,
      },
      "ccs.SingleChatReq",
  };
}
struct SingleChatReqGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr SingleChatReqGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 SingleChatReq_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(SingleChatReq::InternalGenerateClassData_(
            _default, &SingleChatReq_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<SingleChatReq>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~SingleChatReqGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) SingleChatReq _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<SingleChatReq>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(SingleChatReqGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST SingleChatReqGlobalsTypeInternal SingleChatReq_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* SingleChatReq_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return SingleChatReq_globals_.GetClassData();
#else
  return SingleChatReq_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
}  // namespace ccs
namespace ccs {
PROTOBUF_CONSTINIT const uint32_t MessageType_internal_data_[] = {
    458752u, 131072u, 101u, 100u, };
static const char MessageType_names[] = {
    "MT_Audio"
    "MT_Edit"
    "MT_File"
    "MT_Image"
    "MT_None"
    "MT_Pdf"
    "MT_Revoke"
    "MT_Text"
    "MT_Video"
};

static const ::google::protobuf::internal::EnumEntry MessageType_entries[] = {
    {{&MessageType_names[0], 8}, 4},
    {{&MessageType_names[8], 7}, 100},
    {{&MessageType_names[15], 7}, 3},
    {{&MessageType_names[22], 8}, 2},
    {{&MessageType_names[30], 7}, 0},
    {{&MessageType_names[37], 6}, 6},
    {{&MessageType_names[43], 9}, 101},
    {{&MessageType_names[52], 7}, 1},
    {{&MessageType_names[59], 8}, 5},
};

static const int MessageType_entries_by_number[] = {
    4,  // 0 -> MT_None
    7,  // 1 -> MT_Text
    3,  // 2 -> MT_Image
    2,  // 3 -> MT_File
    0,  // 4 -> MT_Audio
    8,  // 5 -> MT_Video
    5,  // 6 -> MT_Pdf
    1,  // 100 -> MT_Edit
    6,  // 101 -> MT_Revoke
};

[[nodiscard]] bool MessageType_Parse(::absl::string_view name,
                                  MessageType* PROTOBUF_NONNULL value) {
  int int_value;
  bool success = ::google::protobuf::internal::LookUpEnumValue(
      MessageType_entries, 9, name, &int_value);
  if (success) {
    *value = static_cast<MessageType>(int_value);
  }
  return success;
}
static ::google::protobuf::internal::ExplicitlyConstructed<::std::string>
    MessageType_strings[9] = {};

[[nodiscard]] const ::std::string& MessageType_Name(MessageType value) {
  static const bool kDummy = ::google::protobuf::internal::InitializeEnumStrings(
      MessageType_entries, MessageType_entries_by_number, 9,
      MessageType_strings);
  (void)kDummy;

  int idx = ::google::protobuf::internal::LookUpEnumName(MessageType_entries,
                                  MessageType_entries_by_number,
                                  9, value);
  return idx == -1 ? ::google::protobuf::internal::GetEmptyString() : MessageType_strings[idx].get();
}
// ===================================================================

SingleChatReq::SingleChatReq(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, SingleChatReq_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ccs.SingleChatReq)
}
PROTOBUF_NDEBUG_INLINE SingleChatReq::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::ccs::SingleChatReq& from_msg)
      : _has_bits_{from._has_bits_},
        cli_uuid_(arena, from.cli_uuid_),
        content_(arena, from.content_) {}

SingleChatReq::SingleChatReq(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SingleChatReq& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, SingleChatReq_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SingleChatReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, to_id_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, to_id_),
           offsetof(Impl_, target_seq_) -
               offsetof(Impl_, to_id_) +
               sizeof(Impl_::target_seq_));

  // @@protoc_insertion_point(copy_constructor:ccs.SingleChatReq)
}
PROTOBUF_NDEBUG_INLINE SingleChatReq::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : cli_uuid_(arena),
        content_(arena) {}

inline void SingleChatReq::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, to_id_),
           0,
           offsetof(Impl_, target_seq_) -
               offsetof(Impl_, to_id_) +
               sizeof(Impl_::target_seq_));
}
SingleChatReq::~SingleChatReq() {
  // @@protoc_insertion_point(destructor:ccs.SingleChatReq)
  SharedDtor(*this);
}
inline void SingleChatReq::SharedDtor(MessageLite& self) {
  SingleChatReq& this_ = static_cast<SingleChatReq&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.cli_uuid_.Destroy();
  this_._impl_.content_.Destroy();
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite SingleChatReq_class_data_ =
    SingleChatReq::InternalGenerateClassData_(SingleChatReq_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SingleChatReq::GetClassData() const {
  return SingleChatReq_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SingleChatReq::GetClassData() const {
  return SingleChatReq_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const SingleChatReq::ParseTableT_
    SingleChatReq::_table_ =
        SingleChatReq::InternalGenerateParseTable_(SingleChatReq_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void SingleChatReq::Clear() {
  auto& this_ [[maybe_unused]] = *this;
  // @@protoc_insertion_point(message_clear_start:ccs.SingleChatReq)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits [[maybe_unused]] = 0;

  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      this_._impl_.cli_uuid_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      this_._impl_.content_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000003cU)) {
    ::memset(&this_._impl_.to_id_, 0,
             static_cast<::size_t>(
                 reinterpret_cast<char*>(&this_._impl_.target_seq_) -
                 reinterpret_cast<char*>(&this_._impl_.to_id_)) +
                 sizeof(_impl_.target_seq_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SingleChatReq::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SingleChatReq& this_ = static_cast<const SingleChatReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SingleChatReq::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SingleChatReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:ccs.SingleChatReq)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string cli_uuid = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_cli_uuid().empty()) {
      const ::std::string& _s = this_._internal_cli_uuid();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ccs.SingleChatReq.cli_uuid");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // uint32 to_id = 2;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_to_id() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          2, this_._internal_to_id(), target);
    }
  }

  // .ccs.MessageType type = 3;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_type() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          3, this_._internal_type(), target);
    }
  }

  // string content = 4;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_content().empty()) {
      const ::std::string& _s = this_._internal_content();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ccs.SingleChatReq.content");
      target = stream->WriteStringMaybeAliased(4, _s, target);
    }
  }

  // int64 target_id = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_target_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<5>(
              stream, this_._internal_target_id(), target);
    }
  }

  // int64 target_seq = 6;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (this_._internal_target_seq() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<6>(
              stream, this_._internal_target_seq(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ccs.SingleChatReq)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SingleChatReq::ByteSizeLong(const MessageLite& base) {
  const SingleChatReq& this_ = static_cast<const SingleChatReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SingleChatReq::ByteSizeLong() const {
  const SingleChatReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:ccs.SingleChatReq)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits [[maybe_unused]] = 0;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    // string cli_uuid = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_cli_uuid().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_cli_uuid());
      }
    }
    // string content = 4;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_content().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_content());
      }
    }
    // uint32 to_id = 2;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_to_id() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_to_id());
      }
    }
    // .ccs.MessageType type = 3;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_type() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_type());
      }
    }
    // int64 target_id = 5;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_target_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_target_id());
      }
    }
    // int64 target_seq = 6;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (this_._internal_target_seq() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_target_seq());
      }
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void SingleChatReq::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<SingleChatReq*>(&to_msg);
  auto& from = static_cast<const SingleChatReq&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:ccs.SingleChatReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_cli_uuid().empty()) {
        _this->_internal_set_cli_uuid(from._internal_cli_uuid());
      } else {
        if (_this->_impl_.cli_uuid_.IsDefault()) {
          _this->_internal_set_cli_uuid("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_content().empty()) {
        _this->_internal_set_content(from._internal_content());
      } else {
        if (_this->_impl_.content_.IsDefault()) {
          _this->_internal_set_content("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_to_id() != 0) {
        _this->_impl_.to_id_ = from._impl_.to_id_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_type() != 0) {
        _this->_impl_.type_ = from._impl_.type_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_target_id() != 0) {
        _this->_impl_.target_id_ = from._impl_.target_id_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (from._internal_target_seq() != 0) {
        _this->_impl_.target_seq_ = from._impl_.target_seq_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}

void SingleChatReq::CopyFrom(const SingleChatReq& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:ccs.SingleChatReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SingleChatReq::InternalSwap(SingleChatReq* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.cli_uuid_, &other->_impl_.cli_uuid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.content_, &other->_impl_.content_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SingleChatReq, _impl_.target_seq_)
      + sizeof(SingleChatReq::_impl_.target_seq_)
      - PROTOBUF_FIELD_OFFSET(SingleChatReq, _impl_.to_id_)>(
          reinterpret_cast<char*>(&_impl_.to_id_),
          reinterpret_cast<char*>(&other->_impl_.to_id_));
}

// ===================================================================

SingleChatRsp::SingleChatRsp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, SingleChatRsp_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ccs.SingleChatRsp)
}
PROTOBUF_NDEBUG_INLINE SingleChatRsp::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::ccs::SingleChatRsp& from_msg)
      : _has_bits_{from._has_bits_},
        cli_uuid_(arena, from.cli_uuid_) {}

SingleChatRsp::SingleChatRsp(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SingleChatRsp& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, SingleChatRsp_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SingleChatRsp* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, seq_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, seq_),
           offsetof(Impl_, code_) -
               offsetof(Impl_, seq_) +
               sizeof(Impl_::code_));

  // @@protoc_insertion_point(copy_constructor:ccs.SingleChatRsp)
}
PROTOBUF_NDEBUG_INLINE SingleChatRsp::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : cli_uuid_(arena) {}

inline void SingleChatRsp::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, seq_),
           0,
           offsetof(Impl_, code_) -
               offsetof(Impl_, seq_) +
               sizeof(Impl_::code_));
}
SingleChatRsp::~SingleChatRsp() {
  // @@protoc_insertion_point(destructor:ccs.SingleChatRsp)
  SharedDtor(*this);
}
inline void SingleChatRsp::SharedDtor(MessageLite& self) {
  SingleChatRsp& this_ = static_cast<SingleChatRsp&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.cli_uuid_.Destroy();
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite SingleChatRsp_class_data_ =
    SingleChatRsp::InternalGenerateClassData_(SingleChatRsp_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SingleChatRsp::GetClassData() const {
  return SingleChatRsp_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SingleChatRsp::GetClassData() const {
  return SingleChatRsp_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const SingleChatRsp::ParseTableT_
    SingleChatRsp::_table_ =
        SingleChatRsp::InternalGenerateParseTable_(SingleChatRsp_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void SingleChatRsp::Clear() {
  auto& this_ [[maybe_unused]] = *this;
  // @@protoc_insertion_point(message_clear_start:ccs.SingleChatRsp)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits [[maybe_unused]] = 0;

  cached_has_bits = this_._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    this_._impl_.cli_uuid_.ClearNonDefaultToEmpty();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000001eU)) {
    ::memset(&this_._impl_.seq_, 0,
             static_cast<::size_t>(
                 reinterpret_cast<char*>(&this_._impl_.code_) -
                 reinterpret_cast<char*>(&this_._impl_.seq_)) +
                 sizeof(_impl_.code_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SingleChatRsp::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SingleChatRsp& this_ = static_cast<const SingleChatRsp&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SingleChatRsp::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SingleChatRsp& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:ccs.SingleChatRsp)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string cli_uuid = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_cli_uuid().empty()) {
      const ::std::string& _s = this_._internal_cli_uuid();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ccs.SingleChatRsp.cli_uuid");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // int32 code = 2;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_code() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
              stream, this_._internal_code(), target);
    }
  }

  // int64 seq = 3;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_seq() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<3>(
              stream, this_._internal_seq(), target);
    }
  }

  // int64 msg_id = 4;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_msg_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<4>(
              stream, this_._internal_msg_id(), target);
    }
  }

  // int64 created_at = 5;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_created_at() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<5>(
              stream, this_._internal_created_at(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ccs.SingleChatRsp)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SingleChatRsp::ByteSizeLong(const MessageLite& base) {
  const SingleChatRsp& this_ = static_cast<const SingleChatRsp&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SingleChatRsp::ByteSizeLong() const {
  const SingleChatRsp& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:ccs.SingleChatRsp)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits [[maybe_unused]] = 0;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    // string cli_uuid = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_cli_uuid().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_cli_uuid());
      }
    }
    // int64 seq = 3;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_seq() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_seq());
      }
    }
    // int64 msg_id = 4;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_msg_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_msg_id());
      }
    }
    // int64 created_at = 5;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_created_at() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_created_at());
      }
    }
    // int32 code = 2;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_code() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_code());
      }
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void SingleChatRsp::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<SingleChatRsp*>(&to_msg);
  auto& from = static_cast<const SingleChatRsp&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:ccs.SingleChatRsp)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_cli_uuid().empty()) {
        _this->_internal_set_cli_uuid(from._internal_cli_uuid());
      } else {
        if (_this->_impl_.cli_uuid_.IsDefault()) {
          _this->_internal_set_cli_uuid("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_seq() != 0) {
        _this->_impl_.seq_ = from._impl_.seq_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_msg_id() != 0) {
        _this->_impl_.msg_id_ = from._impl_.msg_id_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_created_at() != 0) {
        _this->_impl_.created_at_ = from._impl_.created_at_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_code() != 0) {
        _this->_impl_.code_ = from._impl_.code_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}

void SingleChatRsp::CopyFrom(const SingleChatRsp& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:ccs.SingleChatRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SingleChatRsp::InternalSwap(SingleChatRsp* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.cli_uuid_, &other->_impl_.cli_uuid_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SingleChatRsp, _impl_.code_)
      + sizeof(SingleChatRsp::_impl_.code_)
      - PROTOBUF_FIELD_OFFSET(SingleChatRsp, _impl_.seq_)>(
          reinterpret_cast<char*>(&_impl_.seq_),
          reinterpret_cast<char*>(&other->_impl_.seq_));
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace ccs
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
