services:
  portainer:
    image: portainer/portainer-ce
    restart: always
    container_name: portainer-dev
    network_mode: host
    privileged: true
    tty: true
    stdin_open: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
